import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "transparent",
  },
  scrollContainer: {
    flexGrow: 1,
    justifyContent: "center",
    paddingHorizontal: 28,
    paddingVertical: 50,
  },
  header: {
    alignItems: "center",
    marginBottom: 50,
  },
  title: {
    fontSize: 38,
    fontWeight: "900",
    textAlign: "center",
    color: "white",
    marginBottom: 10,
    letterSpacing: -1,
  },
  subtitle: {
    fontSize: 16,
    textAlign: "center",
    color: "rgba(255,255,255,0.7)",
    lineHeight: 24,
    fontWeight: "500",
  },
  formContainer: {
    backgroundColor: "rgba(255,255,255,0.98)",
    borderRadius: 35,
    padding: 30,
    marginBottom: 35,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.15,
    shadowRadius: 20,
    elevation: 12,
  },
  formTitle: {
    fontSize: 26,
    fontWeight: "900",
    color: "#0F172A",
    marginBottom: 28,
    textAlign: "center",
    letterSpacing: -0.5,
  },
  inputContainer: {
    marginBottom: 22,
  },
  label: {
    fontSize: 12,
    fontWeight: "800",
    color: "#64748B",
    marginBottom: 10,
    marginLeft: 4,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  input: {
    backgroundColor: "#F8FAFC",
    borderWidth: 1.5,
    borderColor: "#F1F5F9",
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderRadius: 20,
    fontSize: 16,
    color: "#1E293B",
    fontWeight: "600",
  },
  inputFocused: {
    borderColor: "#3B82F6",
    backgroundColor: "white",
  },
  inputError: {
    borderColor: "#EF4444",
    backgroundColor: "#FEF2F2",
  },
  errorText: {
    color: "#EF4444",
    fontSize: 12,
    marginTop: 8,
    marginLeft: 6,
    fontWeight: "700",
  },
  loginButton: {
    backgroundColor: "#1E3A8A",
    paddingVertical: 18,
    borderRadius: 22,
    alignItems: "center",
    marginTop: 15,
    shadowColor: "#1E3A8A",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 15,
    elevation: 8,
  },
  loginButtonDisabled: {
    backgroundColor: "#94A3B8",
    shadowOpacity: 0,
    elevation: 0,
  },
  loginButtonText: {
    color: "white",
    fontSize: 18,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  registerLink: {
    alignItems: "center",
    marginTop: 30,
  },
  registerText: {
    fontSize: 15,
    color: "rgba(255,255,255,0.7)",
    fontWeight: "500",
  },
  registerLinkText: {
    fontSize: 15,
    color: "#60A5FA",
    fontWeight: "900",
    marginTop: 6,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#0F172A",
  },
  loadingText: {
    fontSize: 16,
    color: "#94A3B8",
    marginTop: 18,
    fontWeight: "600",
  },
  testData: {
    marginTop: 25,
    padding: 18,
    backgroundColor: "#F0F9FF",
    borderRadius: 20,
    borderLeftWidth: 5,
    borderLeftColor: "#3B82F6",
  },
  testDataTitle: {
    fontSize: 15,
    fontWeight: "800",
    color: "#0369A1",
    marginBottom: 8,
  },
  testDataText: {
    fontSize: 13,
    color: "#0369A1",
    lineHeight: 18,
    fontWeight: "500",
  },
  forgotPassword: {
    alignItems: "flex-end",
    marginBottom: 22,
  },
  forgotPasswordText: {
    fontSize: 14,
    color: "#3B82F6",
    fontWeight: "700",
  },
});
